### ISSUE TITLE
Can you update this repository with readme docs and missing files. 

### ISSUE THREAD

**Issue by divya-rakheja** [Gloria2tt/T3M#1]
Hi, 

I would really appreciate if you could please update this repository and share the missing files.

**Comment by Gloria2tt** [comment]
Sure, I'll start sorting after I get off work.

**Comment by divya-rakheja** [comment]
The repository that you have uploaded is incomplete and has some missing files. Can you update those if possible?

**Comment by divya-rakheja** [comment]
Also, if you can upload the pre-trained model folder only?

**Comment by Gloria2tt** [comment]
The missing part is all about the dataset. i'll update the readme file and then you will know how to run it.
